#!/usr/bin/env node
// Phase 1.3 — Per-card coverage dashboard generator.
//
// Reads /tmp/effect-coverage.json (must run effect-coverage.mjs first)
// and writes docs/coverage-dashboard.md with:
//   - summary table by severity / category
//   - one row per (cardId, hookType) registration with category + reason
//   - separate section for cards with effect text but NO handler
//   - by-deck breakdown (when card belongs to a known deck/series)
//
// Usage:
//   node tools/audit/effect-coverage.mjs && node tools/audit/dashboard.mjs

import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..', '..');
const reportPath = '/tmp/effect-coverage.json';
const cardsPath = path.join(REPO_ROOT, 'web', 'data', 'cards.json');
const outputPath = path.join(REPO_ROOT, 'docs', 'coverage-dashboard.md');

if (!fs.existsSync(reportPath)) {
  console.error('Run effect-coverage.mjs first to generate /tmp/effect-coverage.json');
  process.exit(1);
}
const report = JSON.parse(fs.readFileSync(reportPath, 'utf8'));
const cards = JSON.parse(fs.readFileSync(cardsPath, 'utf8'));
const cardById = new Map(cards.map(c => [c.id, c]));

// ─── Build a card → primary owner-name index for "by deck" view ─────────────
function deckBucketOf(card) {
  if (!card) return 'Unknown';
  const tag = card.tag || '';
  const tagStr = typeof tag === 'string' ? tag : JSON.stringify(tag);
  // Map common tags to a deck bucket label
  const tagMap = [
    ['#Promise', 'Promise (EN)'],
    ['#Justice', 'Justice (EN)'],
    ['#Advent',  'Advent (EN)'],
    ['#FLOW GLOW', 'FLOW GLOW'],
    ['#ID3期生', 'ID 3期生'],
    ['#ID2期生', 'ID 2期生'],
    ['#ID1期生', 'ID 1期生'],
    ['#ReGLOSS', 'ReGLOSS'],
    ['#秘密結社holoX', 'holoX'],
    ['#ゲーマーズ', 'Gamers'],
    ['#3期生', 'JP 3期生'],
    ['#4期生', 'JP 4期生'],
    ['#5期生', 'JP 5期生'],
    ['#hololive English -Myth-', 'Myth (EN)'],
    ['#hololive English -Council-', 'Council (EN)'],
    ['#0期生', 'JP 0期生'],
    ['#1期生', 'JP 1期生'],
    ['#2期生', 'JP 2期生'],
  ];
  for (const [t, label] of tagMap) {
    if (tagStr.includes(t)) return label;
  }
  // Fall back to support-card type for non-member cards
  if (card.type?.startsWith('支援')) return 'Support: ' + card.type;
  if (card.type === '吶喊') return 'Yell/Cheer';
  return card.name || card.id;
}

// ─── Aggregate ──────────────────────────────────────────────────────────────
const byDeck = {};
for (const e of report.entries) {
  const card = cardById.get(e.id);
  const bucket = deckBucketOf(card);
  byDeck[bucket] = byDeck[bucket] || { total: 0, byCat: {} };
  byDeck[bucket].total++;
  byDeck[bucket].byCat[e.category] = (byDeck[bucket].byCat[e.category] || 0) + 1;
}

const SEVERITY = {
  'AUTO-PICK-BUG':       'HIGH',
  'NUMBER-MISMATCH':     'HIGH',
  'TARGET-WRONG-SIDE':   'HIGH',
  'COST-IGNORED':        'HIGH',
  'CONDITION-MISSING':   'MED',
  'MULTI-STEP-MISSING':  'MED',
  'UNCLASSIFIED':        'LOW',
  'NO_CARD':             'LOW',
  'CORRECT-VERIFIED':    'INFO',
  'STUB-LOG':            'INFO',
  'DISABLED-FALLTHROUGH':'INFO',
  'NO-TEXT':             'INFO',
  'PASSIVE-INTENT':      'INFO',
  'RULE-MOD':            'INFO',
};

function sevIcon(cat) {
  switch (SEVERITY[cat]) {
    case 'HIGH': return '🔴';
    case 'MED':  return '🟡';
    case 'LOW':  return '🟢';
    default:     return '⚪';
  }
}

// ─── Compose markdown ───────────────────────────────────────────────────────
const md = [];
md.push(`# Effect Handler Coverage Dashboard\n`);
md.push(`> Auto-generated by \`tools/audit/dashboard.mjs\`. Do not edit by hand.\n`);
md.push(`> Source: \`/tmp/effect-coverage.json\` (regenerate via \`node tools/audit/effect-coverage.mjs\`).\n`);
md.push(`> Updated: \`${report.generatedAt}\`\n\n`);

md.push(`## Summary\n`);
md.push(`- **Total cards in cards.json**: ${report.totalCards}`);
md.push(`- **Total handler registrations**: ${report.totalRegistrations}`);
md.push(`- **HIGH severity issues**: ${report.severity.HIGH}`);
md.push(`- **MED severity issues**: ${report.severity.MED}`);
md.push(`- **LOW severity (unclassified)**: ${report.severity.LOW}`);
md.push(`- **INFO (correct / stub / disabled / no-text)**: ${report.severity.INFO}\n`);

md.push(`## By Category\n`);
md.push(`| Category | Severity | Count | % |`);
md.push(`|---|---|---|---|`);
for (const [cat, n] of Object.entries(report.totals).sort((a, b) => b[1] - a[1])) {
  const pct = (n / report.totalRegistrations * 100).toFixed(1);
  md.push(`| ${cat} | ${sevIcon(cat)} ${SEVERITY[cat] || '?'} | ${n} | ${pct}% |`);
}
md.push(``);

md.push(`## By File\n`);
md.push(`| File | Total | HIGH | MED | LOW | INFO |`);
md.push(`|---|---|---|---|---|---|`);
for (const [file, c] of Object.entries(report.byFile).sort((a, b) => b[1].total - a[1].total)) {
  let high = 0, med = 0, low = 0, info = 0;
  for (const [cat, n] of Object.entries(c)) {
    if (cat === 'total') continue;
    const sev = SEVERITY[cat] || 'INFO';
    if (sev === 'HIGH') high += n;
    else if (sev === 'MED') med += n;
    else if (sev === 'LOW') low += n;
    else info += n;
  }
  md.push(`| ${file} | ${c.total} | ${high ? '🔴 '+high : '0'} | ${med ? '🟡 '+med : '0'} | ${low || '0'} | ${info} |`);
}
md.push(``);

md.push(`## Coverage Gaps (cards with effect text but no handler)\n`);
md.push(`| Hook | Covered | Total | % | Missing |`);
md.push(`|---|---|---|---|---|`);
for (const [hook, info] of Object.entries(report.coverageGaps)) {
  const covered = info.hookTotal - info.missing;
  const pct = (covered / info.hookTotal * 100).toFixed(1);
  md.push(`| ${hook} | ${covered} | ${info.hookTotal} | ${pct}% | ${info.missing} |`);
}
md.push(``);

md.push(`## By Deck / Series\n`);
md.push(`(handlers grouped by primary tag of the card)\n`);
md.push(`| Bucket | Total | CORRECT | STUB | HIGH | MED | RULE-MOD |`);
md.push(`|---|---|---|---|---|---|---|`);
for (const [bucket, info] of Object.entries(byDeck).sort((a, b) => b[1].total - a[1].total)) {
  const cv = info.byCat['CORRECT-VERIFIED'] || 0;
  const sl = info.byCat['STUB-LOG'] || 0;
  const high = (info.byCat['AUTO-PICK-BUG']||0) + (info.byCat['NUMBER-MISMATCH']||0) + (info.byCat['TARGET-WRONG-SIDE']||0) + (info.byCat['COST-IGNORED']||0);
  const med = (info.byCat['CONDITION-MISSING']||0) + (info.byCat['MULTI-STEP-MISSING']||0);
  const rm = info.byCat['RULE-MOD'] || 0;
  md.push(`| ${bucket} | ${info.total} | ${cv} | ${sl} | ${high ? '🔴 '+high : '0'} | ${med ? '🟡 '+med : '0'} | ${rm || '0'} |`);
}
md.push(``);

md.push(`## HIGH Severity Issues (priority fix list)\n`);
const highEntries = report.entries.filter(e => SEVERITY[e.category] === 'HIGH').sort((a, b) => a.id.localeCompare(b.id));
if (highEntries.length === 0) {
  md.push(`*None! 🎉*`);
} else {
  md.push(`| Card | Hook | Category | Reason | Real text |`);
  md.push(`|---|---|---|---|---|`);
  for (const e of highEntries) {
    const card = cardById.get(e.id);
    const name = card?.name || '?';
    const text = (e.realText || '').replace(/\|/g, '\\|').slice(0, 80);
    md.push(`| \`${e.id}\` ${name} | ${e.hook} | ${e.category} | ${e.reason} | ${text} |`);
  }
}
md.push(``);

md.push(`## MED Severity Issues\n`);
const medEntries = report.entries.filter(e => SEVERITY[e.category] === 'MED').sort((a, b) => a.id.localeCompare(b.id));
if (medEntries.length === 0) {
  md.push(`*None.*`);
} else {
  md.push(`| Card | Hook | Category | Real text |`);
  md.push(`|---|---|---|---|`);
  for (const e of medEntries) {
    const card = cardById.get(e.id);
    const name = card?.name || '?';
    const text = (e.realText || '').replace(/\|/g, '\\|').slice(0, 80);
    md.push(`| \`${e.id}\` ${name} | ${e.hook} | ${e.category} | ${text} |`);
  }
}
md.push(``);

md.push(`## RULE-MOD Cards (need engine-level support)\n`);
const ruleMods = report.entries.filter(e => e.category === 'RULE-MOD').sort((a, b) => a.id.localeCompare(b.id));
md.push(`| Card | Hook | Real text (excerpt) |`);
md.push(`|---|---|---|`);
for (const e of ruleMods) {
  const card = cardById.get(e.id);
  const name = card?.name || '?';
  const text = (e.realText || '').replace(/\|/g, '\\|').slice(0, 100);
  md.push(`| \`${e.id}\` ${name} | ${e.hook} | ${text} |`);
}
md.push(``);

md.push(`## UNCLASSIFIED Entries (need manual review)\n`);
const unc = report.entries.filter(e => e.category === 'UNCLASSIFIED').sort((a, b) => a.id.localeCompare(b.id));
if (unc.length === 0) {
  md.push(`*None.*`);
} else {
  md.push(`| Card | Hook | File:Line | Real text |`);
  md.push(`|---|---|---|---|`);
  for (const e of unc) {
    const card = cardById.get(e.id);
    const name = card?.name || '?';
    const text = (e.realText || '').replace(/\|/g, '\\|').slice(0, 80);
    md.push(`| \`${e.id}\` ${name} | ${e.hook} | ${e.file}:${e.line} | ${text} |`);
  }
}
md.push(``);

md.push(`---`);
md.push(`*Run \`node tools/audit/effect-coverage.mjs && node tools/audit/dashboard.mjs\` to refresh.*`);
md.push(``);

fs.writeFileSync(outputPath, md.join('\n'));
console.log(`Dashboard written to ${outputPath}`);
console.log(`  - HIGH severity: ${highEntries.length}`);
console.log(`  - MED severity: ${medEntries.length}`);
console.log(`  - RULE-MOD: ${ruleMods.length}`);
console.log(`  - UNCLASSIFIED: ${unc.length}`);
